config/routes.rb
Rails.application.routes.draw do
  resources :languages

  resources :translations

  resources :orders, :only => [:index, :show] do
    get :pay, :on => :member
    get :pay_later, :on => :member
    get :process_payment, :on => :member
    get :cart, :on => :member
    match :setting, :on => :collection, :via => [:get, :patch]
  end

  namespace :xapi do
    resources :orders, :only => [:index, :update]
  end

  get 'cart', :to => 'cart#index', :as => 'cart_index'
  get 'cart/update'
  get 'cart/checkout'
  post 'cart/checkout', :to => 'cart#convert', :as => 'cart_convert'
  get 'cart/:sku', :to => 'cart#add', :as => 'cart_addsku'

  root 'home#index'
  get '/list/:uri', :to => 'home#list', :as => 'home_list'
  get '/show/:uri/:sku', :to => 'home#show', :as => 'home_show'

  devise_for :users
end

app/models/cart.rb
require 'dish'

class Cart
  attr_reader :item_list
  def initialize session
    @session = session
    @item_list = Hash.new
    if session[:cart]
      @item_list = YAML.load(session[:cart]) rescue Hash.new
    end
  end
  def add item
    ci = CartItem.new item
    if @item_list[ci.key]
      @item_list[ci.key].inc
    else
      @item_list[ci.key] = ci
    end
  end
  def remove item
    ci = CartItem.new item
    return if !@item_list[ci.key]
    @item_list[ci.key].dec
    @item_list.delete ci.key if @item_list[ci.key].empty?
  end
  def delete item
    ci = CartItem.new item
    @item_list.delete ci.key
  end
  def count
    @item_list.values.sum(&:count)
  end
  def total
    @item_list.values.sum(&:total)
  end
  def save!
    @session[:cart] = YAML.dump(@item_list)
  end
  def to_order params
    order = Order.new params
    order.shipping = params['shipping'] == 0 ? 0 : 2
    order.shipping = 0 if order.carry_out?
    order.total = total + order.shipping
    order.balance = order.total
    @item_list.each do |key, item|
      o = order.order_items.new
      o.dish_id = item.id
      o.count = item.count
      o.total = item.total
    end
    @session[:cart] = nil
    @item_list = []
    order
  end
end

class CartItem
  attr_reader :name, :count, :key, :uri, :price, :id
  def initialize item
    @id = item.id
    @name = item.local_name
    @uri = item.category.uri
    @price = item.price
    @count = 1
    @key = item.sku
  end
  def inc
    @count += 1
  end
  def dec
    @count -= 1
  end
  def empty?
    @count <= 0
  end
  def total
    @price * @count
  end
  def to_s
    s = []
    s << @name
    s << "x#{@count}" if @count > 0
    s.join ''
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_filter :load_cart
  before_filter :load_sku, :only => [:add, :update]
  before_action :authenticate_user!, :only => [:checkout, :convert]
  def index
    @dishes = Dish.includes(:category)
  end

  def add
    if @item
      @cart.add @item
      @cart.save!
    end
    if params[:js]
      render :plain => 'OK'
    else
      redirect_to :action => :index
    end
  end

  def update
    action = params[:do] || nil
    if @item
      case action
      when 'add', 'remove', 'delete'
        @cart.send action, @item
        @cart.save!
      end
    end
    redirect_to :action => :index
  end

  def checkout
    redirect_to :action => :index if @cart.total < 0.01
    @order = Order.new :address => current_user.address
  end

  def convert
    @order = @cart.to_order order_params
    @order.user = current_user
    @order.save
    redirect_to order_path(@order)
  end

  private
  def load_cart
    @cart = Cart.new session
  end
  def load_sku
    sku = params[:sku]
    @item = Dish.find_by_sku sku
  end
  def order_params
    params.require(:order).permit([:delivery, :address, :shipping])
  end
end

app/views/cart/checkout.html.erb
<div class="cart">
  <div class="container">
    <div class="banner"><h2><%= t('nav.checkout') %></h2></div>
    <table class="table table-bordered">
    <thead><tr>
      <th class="col-sm-6"><%= t('cart.name') %></th>
      <th class="col-sm-3 text-center"><%= t('cart.quantity') %></th>
      <th class="col-sm-3 text-right"><%= t('cart.price') %></th>
    </tr></thead>
    <tbody>
      <% @cart.item_list.each do |sku, item| %>
      <tr>
        <td>
          <%= link_to home_show_path(item.uri, sku) do %>
            <%= item.name %>
          <% end %>
          <span class="pull-right">$<%= "%.2f" % item.price %></span>
        </td>
        <td class="text-center"><%= item.count %></td>
        <td class="text-right">$<%= "%.2f" % item.total %></td>
      </tr>
      <% end %>
    </tbody>
    <tfoot><tr>
      <th><%= t('cart.total') %></th>
      <th class="text-center"><%= @cart.count %></th>
      <th class="text-right">$<%= "%.2f" % @cart.total %></th>
    </tr></tfoot>
    </table>

    <hr/>
    <div class="row">
    <%= simple_form_for @order, :url => cart_convert_path do |f| %>
      <div class="col-sm-4">
        <%= f.input :delivery, :collection => Order.delivery_options, :as => :radio_buttons, :value_method => :first, :label_method => :second, :wrapper => :radio %>
      </div>
      <div class="col-sm-4">
        <%= f.input :shipping, :collection => Order.shipping_options, :as => :radio_buttons, :value_method => :first, :label_method => :second, :wrapper => :radio %>
      </div>
      <div class="col-sm-4">
      <%= f.input :address, :as => :text, :input_html => {:class => 'form-control'} %>
      </div>
      <div class="col-sm-12 text-center">
        <%= f.submit :class => 'btn btn-primary' %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/cart/index.html.erb
<div class="cart">
  <div class="container">
    <div class="banner"><h2><%= t('nav.cart') %></h2></div>
    <table class="table table-bordered">
    <thead><tr>
      <th class="col-sm-5"><%= t('cart.name') %></th>
      <th class="col-sm-4 text-center"><%= t('cart.quantity') %></th>
      <th class="col-sm-3 text-right"><%= t('cart.price') %></th>
    </tr></thead>
    <tbody>
      <% @cart.item_list.each do |sku, item| %>
      <tr>
        <td>
          <%= link_to home_show_path(item.uri, sku) do %>
            <span class="dish" data-toggle="tooltip" data-placement="bottom"
            data-title="<%= render_title item %>">
              <%= item.name %>
            </span>
          <% end %>
          <span class="pull-right">$<%= "%.2f" % item.price %></span>
        </td>
        <td class="row cart_quantity">
          <div class="col-xs-4 col-sm-4 text-right">
            <%= link_to cart_update_path(:sku => sku, :do => 'remove') do %>
              <i class="fa fa-minus"></i>
            <% end %>
          </div>
          <div class="col-xs-4 col-sm-2 text-right"><%= item.count %></div>
          <div class="col-xs-4 col-sm-3">
            <%= link_to cart_update_path(:sku => sku, :do => 'add') do %>
              <i class="fa fa-plus"></i>
            <% end %>
          </div>
          <div class="col-sm-3 hidden-xs text-right">
            <%= link_to cart_update_path(:sku => sku, :do => 'delete') do %>
              <i class="fa fa-close"></i>
            <% end %>
          </div>
        </td>
        <td class="text-right">$<%= "%.2f" % item.total %></td>
      </tr>
      <% end %>
    </tbody>
    <tfoot><tr>
      <th><%= t('cart.total') %></th>
      <th class="text-center"><%= @cart.count %></th>
      <th class="text-right">$<%= "%.2f" % @cart.total %></th>
    </tr></tfoot>
    </table>
    <% if @cart.total >= 0.01 %>
      <%= link_to t('nav.checkout'), cart_checkout_path, :class => 'btn btn-primary pull-right' %>
    <% end %>
  </div>
</div>