config/routes.rb
Rails.application.routes.draw do
  resources :languages

  resources :translations

  resources :orders, :only => [:index, :show] do
    get :pay, :on => :member
    get :pay_later, :on => :member
    get :process_payment, :on => :member
    get :cart, :on => :member
    match :setting, :on => :collection, :via => [:get, :patch]
  end

  namespace :xapi do
    resources :orders, :only => [:index, :update]
  end

  get 'cart', :to => 'cart#index', :as => 'cart_index'
  get 'cart/update'
  get 'cart/checkout'
  post 'cart/checkout', :to => 'cart#convert', :as => 'cart_convert'
  get 'cart/:sku', :to => 'cart#add', :as => 'cart_addsku'

  root 'home#index'
  get '/list/:uri', :to => 'home#list', :as => 'home_list'
  get '/show/:uri/:sku', :to => 'home#show', :as => 'home_show'

  devise_for :users
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  respond_to :html
  def index
    respond_with @categories = Category.order(:position => :asc).includes(:dishes)
  end

  def list
    uri = params[:uri]
    @category = Category.find_by_uri(uri)
    if @category.nil?
      redirect_to root_path
      return
    end
    respond_with @category
  end

  def show
    sku = params[:sku]
    @dish = Dish.find_by_sku(sku)
    if @dish.nil?
      redirect_to root_path
      return
    end
    respond_with @dish
  end
end

app/views/home/index.html.erb
<div class="inner-menu">
  <div class="container">
    <div class="banner"><h2><%= t('nav.menu') %></h2></div>
    <div class="row">
    <% @categories.each_with_index do |c, i| %>
      <div class="col-md-4 col-sm-6">
        <div class="menu-list">
          <h3><%= link_to home_list_path(c.uri) do %>
            <%= c.chinese %> / <%= c.english %>
            <% end %>
          </h3>
          <img class="img-responsive" src="img/menu/<%= c.uri %>.jpg" alt="">
          <% c.dishes.each do |dish| %>
            <div class="menu-list-item <%= dish == c.dishes.last ? 'border-zero' : '' %>">
              <!-- Heading / Dish name -->
              <h4 class="pull-left">
                <%= link_to home_show_path(c.uri, dish.sku) do %>
                  <%= dish.local_name %>
                <% end %>
              </h4>
              <%= link_to fa_icon('cart-plus lg'), cart_addsku_path(dish.sku, :js => true), :class => 'text-primary cartplus' %>
              <!-- Dish price -->
              <span class="price pull-right">$<%= "%.2f" % dish.price %></span>
              <div class="clearfix"></div>
            </div>
          <% end %>
        </div>
      </div>
      <% if i.odd? %>
        <div class="clearfix_2col"></div>
      <% end %>
    <% end %>
    </div>
  </div>
</div>

app/views/home/list.html.erb
<div class="shopping">
  <div class="container">
    <div class="banner"><h2><%= @category.local_name %></h2></div>
    <div class="shopping-content">
      <div class="row">
      <% @category.dishes.each do |dish| %>
        <div class="col-lg-4 col-sm-6">
          <!-- Shopping items -->
          <div class="shopping-item">
            <!-- Image -->
            <%= link_to home_show_path(@category.uri, dish.sku) do %>
              <img class="img-responsive" src="/img/dish/dish.jpg" alt="" />
            <% end %>
            <!-- Shopping item name / Heading -->
            <h4 class="pull-left">
              <%= link_to home_show_path(@category.uri, dish.sku) do %>
                <%= dish.local_name %>
              <% end %>
            </h4>
            <span class="item-price pull-right">$<%= "%.2f" % dish.price %></span>
            <div class="clearfix"></div>
            <!-- Paragraph -->
            <p><%= dish.description %></p>
            <!-- Buy now button -->
            <div class="visible-xs">
              <a class="btn btn-danger btn-sm" href="#"><%= t('cart.add_to_cart') %></a>
            </div>
            <!-- Shopping item hover block & link -->
            <div class="item-hover br-red hidden-xs"></div>
            <%= link_to t('cart.add_to_cart'), cart_addsku_path(dish.sku), :class => 'link hidden-xs' %>
            <!-- Hot tag -->
            <!--span class="hot-tag br-green">New</span-->
          </div>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/show.html.erb
<div class="single-item">
  <div class="container">
    <!-- Shopping single item contents -->
    <div class="single-item-content">
      <div class="row">
        <div class="col-md-5 col-sm-6">
          <!-- Product image -->
          <img class="img-responsive img-thumbnail" src="/img/dish/dish.jpg" alt="">
        </div>
        <div class="col-md-7 col-sm-6">
          <!-- Heading -->
          <h3><%= @dish.local_name %></h3>
          <div class="row">
            <div class="col-xs-7">
              <%= link_to fa_icon('cart-plus lg', :text => t('cart.add_to_cart')), cart_addsku_path(@dish.sku), :class => 'btn btn-danger' %>
            </div>
            <div class="col-xs-5"><span class="item-price">$<%= "%.2f" % @dish.price %></span></div>
          </div>
          <!-- Single item details -->
          <div class="item-details">
            <!-- Paragraph -->
            <p class="text-justify"><%= @dish.description %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>