config/routes.rb
Rails.application.routes.draw do
  resources :languages

  resources :translations

  resources :orders, :only => [:index, :show] do
    get :pay, :on => :member
    get :pay_later, :on => :member
    get :process_payment, :on => :member
    get :cart, :on => :member
    match :setting, :on => :collection, :via => [:get, :patch]
  end

  namespace :xapi do
    resources :orders, :only => [:index, :update]
  end

  get 'cart', :to => 'cart#index', :as => 'cart_index'
  get 'cart/update'
  get 'cart/checkout'
  post 'cart/checkout', :to => 'cart#convert', :as => 'cart_convert'
  get 'cart/:sku', :to => 'cart#add', :as => 'cart_addsku'

  root 'home#index'
  get '/list/:uri', :to => 'home#list', :as => 'home_list'
  get '/show/:uri/:sku', :to => 'home#show', :as => 'home_show'

  devise_for :users
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items
  belongs_to :user
  has_many :payments
  enum :delivery => [:carry_out, :delivery]
  enum :status => [:created, :paid, :printed]
  scope :valid, -> { where('status BETWEEN 1 AND 3') }
  def valid_payments
    payments.where('status > 0')
  end

  def expired?
    created? && created_at < 6.hours.ago
  end

  def self.delivery_options
    deliveries.keys.map{|k| [k, I18n.t(k)]}
  end

  def self.shipping_options
    [[0, I18n.t(:on_campus_free)], [1, I18n.t(:in_town)]]
  end

  def as_json(options = {})
    super :include => {
        :order_items => {
          :only => [:id, :count, :total],
          :include => {
            :dish => {
              :only => [:chinese, :english, :sku, :price]
            }
          }
        },
        :valid_payments => {}
      }
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  respond_to :html
  before_action :authenticate_user!
  before_filter :find_order, :only => [:show, :pay, :pay_later, :process_payment, :cart]
  include PayPal::SDK
  def index
    respond_with @orders = current_user.orders.includes(:order_items => {:dish => :category}).paginate(:page => params[:page], :per_page => 15).order('id DESC')
  end

  def setting
    if params[:user]
      u = User.find(current_user)
      u.update_attributes user_params
      redirect_to setting_orders_path
    end
  end
  def user_params
    params.require(:user).permit([:mobile, :address, :wechat, :birthday])
  end

  def show
    if @order.nil?
      redirect_to :action => :index
      return
    end
    respond_with @order
  end

  def pay
    if @order.paid?
      redirect_to order_path(@order)
      return
    end
    if @order.balance < 0.01
      @order.paid!
      redirect_to order_path(@order)
      return
    end
    if @order.nil?
      redirect_to :action => :index
      return
    end
    @payment = REST::Payment.new({
      :intent => "sale",
      :payer => {
        :payment_method => "paypal" },
      :redirect_urls => {
        :return_url => process_payment_order_url(@order),
        :cancel_url => process_payment_order_url(@order) },
      :transactions => [ {
        :amount => {
          :total => "%.2f" % @order.balance,
          :currency => "USD" },
        :description => "Online Menu Order" } ] } )

    if @payment.create
      @redirect_url = @payment.links.find{|v| v.method == "REDIRECT" }.href
      @order.paypal_payment_id = @payment.id
      @order.save
      @order.payments.create :payment_id => @payment.id, :amount => @order.balance
      redirect_to @redirect_url
    else
      redirect_to order_path(@order)
    end
  end

  def pay_later
    @order.paid!
    redirect_to order_path(@order)
  end

  def process_payment
    # http://10.0.1.40/orders/1/process_payment?token=EC-7040590647086154P&PayerID=2E8ZE9J9VR6T8
    payment = REST::Payment.find(@order.paypal_payment_id)

    if payment.execute(:payer_id => params[:PayerID])
      flash[:success] = "Paid"
      payment_total = payment.transactions.first.amount.total
      @order.balance -= payment_total.to_f
      @order.paid! if @order.balance < 0.01
      p = @order.payments.find_by_payment_id(@order.paypal_payment_id)
      if p
        p.payer_id = params[:PayerID]
        p.paid!
        p.save
      end
      @order.save
      # Success Message
      # Note that you'll need to `Payment.find` the payment again to access user info like shipping address
    else
      flash[:error] = payment.error # Error Hash
    end
    redirect_to order_path(@order)
  end

  def cart
    @cart = Cart.new session
    @order.order_items.each do |i|
      i.count.times { |n| @cart.add i.dish }
    end
    @cart.save!
    redirect_to cart_index_path
  end

  private
  def find_order
    @order = current_user.orders.includes(:order_items => {:dish => [:category]}).find_by_id(params[:id])
  end
end

app/controllers/xapi/orders_controller.rb
class Xapi::OrdersController < ApplicationController
  respond_to :json
  def index
    @orders = Order.valid.includes([{:order_items => [:dish]}, :payments]).order(:updated_at)
    respond_with @orders
  end
end

app/helpers/order_helper.rb
module OrderHelper
  def time_to_s time
    time.strftime '%m/%d/%y %H:%M'
  end
  def show_label order
    if order.paid?
      if order.balance > 0.01
        return content_tag 'span', 'Pay on delivery', :class => 'label label-normal'
      else
        return content_tag 'span', 'Paid', :class => 'label label-success'
      end
    end
    return content_tag 'span', 'Order Received', :class => 'label label-normal' if order.printed?
    return content_tag 'span', 'Expired', :class => 'label label-default' if order.expired?
    
    (link_to t('order.pay_later'), pay_later_order_path(order), :class => 'btn btn-primary btn-xs') + ' ' + (link_to fa_icon('cc-paypal 2x', :class => 'text-primary'), pay_order_path(order))
  end
end

app/views/orders/index.html.erb
<div class="cart" id="orders">
  <div class="container">
    <div class="banner"><h2><%= t('nav.orders') %></h2>
    <%= link_to t('order.settings'), setting_orders_path, :class => 'btn btn-default pull-right' %>
    </div>
    <table class="table table-bordered">
    <thead><tr>
      <th class="col-sm-1">ID</th>
      <th class="col-sm-3 text-center">Date</th>
      <th class="col-sm-5">Content</th>
      <th class="col-sm-3 text-right">Price</th>
    </tr></thead>
    <tbody>
      <% @orders.each do |order| %>
      <tr>
        <td>#<%= order.id %> <span class="show-xs hidden-sm hidden-md hidden-lg text-primary"><%= time_to_s order.created_at %></span></td>
        <td class="text-center hidden-xs"><%= time_to_s order.created_at %></td>
        <td><%= link_to order_path(order) do %>
          <% order.order_items.each do |i| %>
            <span class="dish" data-toggle="tooltip" data-placement="bottom"
            data-title="<%= render_title i.dish %>">
            <%= i.dish.local_name %>
            <% if i.count > 1 %>
              x<%= i.count %>
            <% end %></span>
          <% end %>
        <% end %></td>
        <td class="text-right">
        <%= show_label order %>
        $<%= "%.2f" % order.total %></td>
      </tr>
      <% end %>
    </tbody>
    </table>
    <div class="row">
    <%= will_paginate @orders, :class => 'pull-right', :renderer => BootstrapPagination::Rails %>
    </div>
  </div>
</div>

app/views/orders/setting.html.erb
<div class="cart booking-form">
  <div class="container">
    <div class="banner"><h2><%= t('order.settings') %></h2></div>

<%= simple_form_for(current_user, url: setting_orders_path) do |f| %>
  <div class="form-inputs">
    <%= f.input :mobile, required: false, autofocus: true %>
    <%= f.input :address, required: false %>
    <%= f.input :wechat, required: false %>
    <%= f.input :birthday, required: false %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Save" %>
  </div>
<% end %>

  </div>
</div>

app/views/orders/show.html.erb
<div class="cart">
  <div class="container">
    <div class="banner">
      <%= link_to fa_icon('chevron-left', :text => t('order.back')), orders_path, :class => 'btn btn-primary btn-sm pull-left' %>
      <h2>Order <%= @order.id %></h2>
      <span class="pull-right">
        <%= show_label @order %>
      </span>
    </div>
    <table class="table table-bordered">
    <thead><tr>
      <th class="col-sm-6"><%= t('cart.name') %></th>
      <th class="col-sm-3 text-center"><%= t('cart.quantity') %></th>
      <th class="col-sm-3 text-right"><%= t('cart.price') %></th>
    </tr></thead>
    <tbody>
      <% @order.order_items.each do |i| %>
      <tr>
        <td>
          <span class="dish" data-toggle="tooltip" data-placement="bottom"
          data-title="<%= render_title i.dish %>">
          <%= i.dish.local_name %>
          </span>
        </td>
        <td class="text-center"><%= i.count %></td>
        <td class="text-right">$<%= "%.2f" % (i.total) %></td>
      </tr>
      <% end %>
      <tr>
        <td><%= @order.delivery %></td>
        <td></td>
        <td class="text-right">$<%= "%.2f" % @order.shipping %></td>
      </tr>
    </tbody>
    <tfoot><tr>
      <th>Total:</th>
      <th></th>
      <th class="text-right">$<%= "%.2f" % @order.total %></th>
    </tr>
      <% @order.valid_payments.each do |p| %>
      <tr class="success">
        <td>PayPal: <%= p.payment_id %></td>
        <td></td>
        <td class="text-right">$<%= "%.2f" % p.amount %></td>
      </tr>
      <% end %>
    </tfoot>
    </table>
    <div class="pull-right">
      <% if !@order.paid? && !@order.expired? %>
        <%= link_to fa_icon('cc-paypal 2x', :text => t('cart.pay'), :class => 'text-primary'), pay_order_path(@order), :class => 'btn btn-default' %>
      <% end %>
      <%= link_to fa_icon('cart-plus lg', :text => t('cart.add_to_cart')), cart_order_path(@order), :class => 'btn btn-default' %>
    </div>
  </div>
</div>