config/routes.rb
Rails.application.routes.draw do
  resources :languages

  resources :translations

  resources :orders, :only => [:index, :show] do
    get :pay, :on => :member
    get :pay_later, :on => :member
    get :process_payment, :on => :member
    get :cart, :on => :member
    match :setting, :on => :collection, :via => [:get, :patch]
  end

  namespace :xapi do
    resources :orders, :only => [:index, :update]
  end

  get 'cart', :to => 'cart#index', :as => 'cart_index'
  get 'cart/update'
  get 'cart/checkout'
  post 'cart/checkout', :to => 'cart#convert', :as => 'cart_convert'
  get 'cart/:sku', :to => 'cart#add', :as => 'cart_addsku'

  root 'home#index'
  get '/list/:uri', :to => 'home#list', :as => 'home_list'
  get '/show/:uri/:sku', :to => 'home#show', :as => 'home_show'

  devise_for :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_i18n

  def set_i18n
    Translation.lang = session[:lang] || detect_locale
    I18n.locale = Translation.lang == :Chinese ? :cn : :en
  end

  def detect_locale
    return :Chinese if request.env['HTTP_ACCEPT_LANGUAGE'].include? 'zh' rescue :English
    :English
  end
end

app/views/application/_footer.html.erb
<div class="footer padd">
  <div class="container">
    <div class="row">
      <div class="col-sm-10 col-xs-8">
        <div class="footer-widget">
          <div class="contact-details row">
            <div class="col-sm-4">
              <i class="fa fa-map-marker br-red"></i> <span>155 NW Kings Blvd<br>Corvallis, OR 97330</span>
              <div class="clearfix"></div>
            </div>
            <div class="col-sm-4">
              <i class="fa fa-phone br-green"></i> <span>(609) 865-5016</span>
              <div class="clearfix"></div>
            </div>
            <div class="col-sm-4">
              <i class="fa fa-envelope-o br-lblue"></i> <span><a href="#">i[at]yihotpot.com</a></span>
              <div class="clearfix"></div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-2 col-xs-4">
        <div class="footer-widget">
          <div class="social">
            <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
            <a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a>
          </div>
        </div>
      </div>
    </div>
    <!-- Copyright -->
    <div class="footer-copyright">
      <!-- Paragraph -->
      <p>© Copyright 2014 Number One Hot Pot</p>
    </div>
  </div>
</div>

app/views/application/_navbar.html.erb
<div class="header">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-sm-5 col-xs-12">
        <!-- Link -->
        <a href="/">
          <!-- Logo area -->
          <div class="logo">
            <!--img class="img-responsive" src="img/logo.png" alt=""-->
            <h1>壹号火锅</h1>
            <p>Chinese foods.</p>
          </div>
        </a>
      </div>
      <div class="col-md-8 col-sm-7 col-xs-12">
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-right" role="navigation">
          <div class="container-fluid">
            <!-- Collect the nav links, forms, and other content for toggling -->
            <ul class="nav navbar-nav">
              <li><%= link_to root_path do %><img src="/img/nav/menu.jpg" class="img-responsive" alt=""><%= t('nav.menu') %><% end %></li>
              <li><%= link_to orders_path do %><img src="/img/nav/order.jpg" class="img-responsive" alt=""><%= t('nav.orders') %><% end %></li>
              <li><%= link_to cart_index_path do %><img src="/img/nav/cart.png" class="img-responsive" alt=""><%= t('nav.cart') %><% end %></li>
              <li><a href="/about"><img src="/img/nav/about.jpg" class="img-responsive" alt=""><%= t('nav.about') %></a></li>
            </ul>
          </div><!-- /.container-fluid -->
        </nav>
      </div>
    </div>
  </div>
</div>